name: Docker_Build_Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-push-docker-images:
    runs-on: ubuntu-latest
    outputs: 
      image_version: ${{github.sha}}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Docker build setup
        uses: docker/setup-buildx-action@v3

      - name: List the files and current working directory
        run: |
          pwd
          ls -lthr
      # This step runs only upto the test stage
      - name: Run the unit test
        run: |
          docker build --no-cache --target test -t myapp:test .

      # This step runs only if the unit test passes
      - name: Login to DockerHUB
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker build local image
      - name: Build local image for scanning
        run: |
          docker build --no-cache -t 'nodeapp:${{github.sha}}' .

      - name: List the files and current working directory
        run: |
          pwd
          ls -lthr
          cat package.json
          grep '"glob"' package-lock.json

      # This crashes the pipeline if vulnerabilities are found
      - name: scan the image for vulnurabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: "nodeapp:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      # Push the image to DockerHub
      - name: Push image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/nodeapp:${{ github.sha }}

  deploy-to-kubernetes-Dev-env:
    needs: build-push-docker-images
    uses: mniranjanr7/k8s-deployments/.github/workflows/actions.yaml@main
    with:
      image_version: ${{ needs.build-push-docker-images.outputs.image_version }}
      environment: dev
      deploy_strategy: "blue"
    secrets:
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

  deploy-to-kubernetes-test-env:
    needs: deploy-to-kubernetes-Dev-env
    environment: test
    uses: mniranjanr7/k8s-deployments/.github/workflows/actions.yaml@main
    with:
      image_version: ${{ needs.build-push-docker-images.outputs.image_version }}
      deploy_strategy: "blue"
      environment: test
    secrets:
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
